name: Continuous Delivery

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ latest ]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node }} 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies 👨🏻‍💻
        run: npm ci
      - name: Generate ⚙️
        run: npm run generate
      - name: Create .nojekyll file 🧪
        run: touch ./dist/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          single-commit: true
